### PR TITLE
DEV-3720 - Carousel Accessibility

### PR DESCRIPTION
**Pull request by mrtimbrook**
This PR is for the base branch for all of the carousel accessibility tasks. 

Once a task is completed it is to be merged into this branch and then when all tasks are complete the version should be bumped and this branch merged to master.

### CODE REVIEW

**Review by abrin — COMMENTED** [review]
Not sure if this is the right moment to get started here... but looking at the Aria labels, is it possible to pull these out as a set of props and/or properly handle internationalization?

**Comment by mrtimbrook** [comment]
@abrin Sorry I missed your comment. I had discussed this with Matthew and I believe we were going to tackle it after all the a11y updates were complete.

**Comment by mrtimbrook** [comment]
This is ready for review. It includes all of the carousel a11y tasks apart from DEV-3734 which is marked to discuss with Sina.

**Comment by abrin** [comment]
@mrtimbrook  no worries

**Review by mphstudios — DISMISSED** [review]

**Comment by mphstudios** [comment]
Before merge this needs a version increment.

**Review by mphstudios — APPROVED** [review]

**Pull request merged**
